# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 11:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2018, 2, 1, 19, 8, 13, 545000))),
                ('Black', models.CharField(choices=[('1', 'player1'), ('2', 'player2')], default='1', max_length=2)),
                ('Founder', models.CharField(choices=[('1', 'player1'), ('2', 'player2')], default='1', max_length=2)),
                ('p1_message', models.TextField(default='', max_length=800)),
                ('p2_message', models.TextField(default='', max_length=800)),
                ('all_steps', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='GameMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black', models.BooleanField(default=True)),
                ('info', models.CharField(max_length=5)),
                ('game_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app2.GameInfo')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('r', 'ready'), ('b', 'busy'), ('r', 'rest')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserHomeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('inviting', 'is inviting'), ('invited', 'is invited'), ('accepted', "'s invitation is accept")], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('age', models.SmallIntegerField(default=0)),
                ('strength', models.CharField(choices=[('18k', '18k'), ('17k', '17k'), ('16k', '16k'), ('15k', '15k'), ('14k', '14k'), ('13k', '13k'), ('12k', '12k'), ('11k', '11k'), ('10k', '10k'), ('9k', '9k'), ('8k', '8k'), ('7k', '7k'), ('6k', '6k'), ('5k', '5k'), ('4k', '4k'), ('3k', '3k'), ('2k', '2k'), ('1k', '1k'), ('1d', '1d'), ('2d', '2d'), ('3d', '3d'), ('4d', '4d'), ('5d', '5d'), ('6d', '6d'), ('7d', '7d'), ('8d', '8d'), ('9d', '9d'), ('10d', '10d')], default='18k', max_length=4)),
                ('description', models.CharField(default='', max_length=200)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='userhomemessage',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.UserInfo'),
        ),
        migrations.AddField(
            model_name='userhomemessage',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='app2.UserInfo'),
        ),
        migrations.AddField(
            model_name='onlineuserlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app2.UserInfo'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='app2.UserInfo'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='app2.UserInfo'),
        ),
    ]
