# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinfo',
            old_name='all_steps',
            new_name='steps',
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 19, 31, 29, 526000)),
        ),
    ]
